#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

python manage.py migrate --no-input
python manage.py collectstatic --no-input
# exec python manage.py runserver 0.0.0.0:8000
DJANGO_SETTINGS_MODULE=ganjineh_api.settings.local uvicorn ganjineh_api.asgi:application --host 0.0.0.0 --port 8000 --reload

