# Generated by Django 4.2 on 2024-05-18 19:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usersubscription",
            name="expires_at",
        ),
    ]
