# Generated by Django 4.2 on 2024-05-19 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0002_remove_usersubscription_expires_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersubscription",
            name="monthly_limit_expiry",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="usersubscription",
            name="monthly_limit_increase",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="CreditIncreaseRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("increase_amount", models.PositiveIntegerField()),
                ("is_approved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("approved_at", models.DateTimeField(auto_now=True)),
                (
                    "user_subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credit_increase_requests",
                        to="subscriptions.usersubscription",
                    ),
                ),
            ],
        ),
    ]
