# Generated by Django 4.2 on 2024-05-20 15:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0003_usersubscription_monthly_limit_expiry_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usersubscription",
            name="credits_remaining",
        ),
    ]
