# Generated by Django 4.2 on 2024-05-21 13:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0004_remove_usersubscription_credits_remaining"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionplan",
            name="monthly_credit_increase",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="usersubscription",
            name="daily_usage",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="usersubscription",
            name="last_usage_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
