# Generated by Django 4.2 on 2024-05-21 13:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0002_alter_profile_user_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="credits_remaining",
        ),
    ]
