# Generated by Django 4.2 on 2024-05-21 15:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0003_remove_profile_credits_remaining"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="allowed_daily_credits",
            field=models.PositiveBigIntegerField(default=10),
        ),
        migrations.AddField(
            model_name="profile",
            name="spent_daily_credits",
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
