# Generated by Django 4.2 on 2024-05-21 19:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0004_profile_allowed_daily_credits_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="monthly_increased_credits",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="profile",
            name="monthly_limit_expiry",
            field=models.DateField(blank=True, null=True),
        ),
    ]
