build:
	docker compose -f docker-compose.dev.yml build -d --remove-orphans

vbuild:
	docker compose -f docker-compose.dev.yml up --build --remove-orphans

up:
	docker compose -f docker-compose.dev.yml up -d

vup:
	docker compose -f docker-compose.dev.yml up

down:
	docker compose -f docker-compose.dev.yml down

down-v:
	docker compose -f docker-compose.dev.yml down -v
